
# Список городов
city = {'Москва': 'moskva',
          'Санкт-Петербург': 'spb',
          'Барнаул': 'barnaul',
          'Владивосток': 'vladivostok',
          'Волгоград': 'volgograd',
          'Воронеж': 'voronezh',
          'Екатеринбург': 'ekaterinburg',
          'Ижевск': 'izhevsk',
          'Казань': 'kazan',
           'Краснодар': 'krasnodar',
          'Красноярск': 'krasnoyarsk',
          'Нижний Новгород': 'nnovgorod',
          'Новосибирск': 'novosibirsk',
          'Омск': 'omsk',
          'Пермь': 'perm',
          'Ростов-на-Дону': 'rostov-na-donu',
          'Самара': 'samara',
           'Саратов': 'saratov',
           'Тольятти': 'tolyatti',
          'Ульяновск': 'ulyanovsk',
          'Уфа': 'ufa',
          'Челябинск': 'chelyabinsk',
          'Ярославль': 'yaroslavl'}
